version: '3.7'

services:

  mongodb:
    image: mongo
    restart: always
    container_name: MongoDB
    ports:
      - 27017:27017
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data-mongo:/data/db
    # command: mongod --auth

volumes:
  data-mongo:
    name: data-mongo
    driver: local
